import {chromium} from '@playwright/test';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const data=JSON.parse(await readFile('public/data/news.json','utf8'));
await mkdir('qa/polished',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},locale:'es-CL'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const url=process.env.QA_URL||'http://127.0.0.1:4173/';
await page.goto(url);await page.getByRole('heading',{name:'Noticias de IA',exact:true}).waitFor();await page.evaluate(()=>document.fonts.ready);
assert.equal(await page.locator('.news-cover').count(),12);
const positions=await page.evaluate(()=>['.archive-masthead','.project-intro','.archive-controls','.archive-results'].map(s=>document.querySelector(s).getBoundingClientRect().top));assert.deepEqual(positions,[...positions].sort((a,b)=>a-b));
await page.screenshot({path:'qa/polished/01-portada.png',fullPage:true});
await page.getByRole('button',{name:'Mostrar más noticias'}).click();assert.equal(await page.locator('.news-cover').count(),data.articles.length);
await page.getByRole('button',{name:'Vista lista'}).click();assert.equal(await page.locator('.news-list-item').count(),data.articles.length);
await page.screenshot({path:'qa/polished/02-lista.png',fullPage:true});
await page.getByRole('searchbox').fill('CREAR imagenes');assert.equal(await page.locator('.news-list-item').count(),1);
await page.getByRole('searchbox').fill('zzznothing');await page.getByRole('heading',{name:'No hay noticias con esos filtros'}).waitFor();await page.locator('.empty').getByRole('button',{name:'Limpiar filtros'}).click();
await page.getByRole('button',{name:'Google',exact:true}).click();await page.getByRole('button',{name:'Modelos',exact:true}).click();assert.equal(await page.locator('.news-list-item').count(),2);
await page.getByRole('button',{name:'Vista portadas'}).click();assert.equal(await page.locator('.news-cover').count(),2);
await page.getByRole('button',{name:/^septiembre de 2026$/i}).click();assert.equal(await page.locator('.news-cover').count(),1);
await page.getByRole('button',{name:'Limpiar filtros',exact:true}).click();
await page.getByLabel('Filtrar por día').fill('2026-09-01');assert.equal(await page.locator('.news-cover').count(),2);
await page.reload();await page.locator('.news-cover').first().waitFor();assert.equal(await page.getByLabel('Filtrar por día').inputValue(),'2026-09-01');assert.equal(await page.locator('.news-cover').count(),2);
await page.screenshot({path:'qa/polished/03-dia.png',fullPage:true});
await page.getByLabel('Filtrar por día').fill('2026-09-02');await page.getByText('Este día todavía no tiene noticias verificadas',{exact:false}).waitFor();
await page.locator('.filter-summary').getByRole('button',{name:'Limpiar filtros'}).click();
await page.getByRole('searchbox').fill('Decisions');await page.locator('.news-cover').click();await page.getByRole('heading',{name:'Consulta la fuente original'}).waitFor();
assert.match(page.url(),/#articulo\/decisions-api$/);assert.equal(await page.locator('h1').textContent(),data.articles.find(a=>a.id==='decisions-api').title);
await page.getByRole('button',{name:'Copiar enlace'}).click();await page.locator('.toast').getByText(/Enlace copiado|Puedes copiar/).waitFor();
await page.screenshot({path:'qa/polished/04-articulo.png',fullPage:true});
await page.reload();await page.getByRole('heading',{name:'Consulta la fuente original'}).waitFor();await page.getByRole('link',{name:'Volver a la portada',exact:true}).click();assert.equal(await page.getByRole('searchbox').inputValue(),'Decisions');
await page.getByRole('button',{name:'Limpiar filtros'}).click();
for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow ${width}`);}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'qa/polished/05-movil.png',fullPage:true});
await page.locator('.news-cover').first().click();await page.getByRole('heading',{name:'Consulta la fuente original'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.goto(url+'#articulo/no-existe');await page.getByRole('heading',{name:'Esta página no está en el archivo'}).waitFor();await page.getByRole('link',{name:'Volver a la portada',exact:true}).click();await page.keyboard.press('Tab');
await page.locator('.skip').focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'contenido');
// Synthetic fixtures stay inside this browser test; they are never published.
const stress=await browser.newPage();await stress.route('**/data/news.json',r=>r.fulfill({json:{...data,articles:Array.from({length:60},(_,i)=>({...data.articles[0],id:`feature-${String(i).padStart(2,'0')}`,eventKey:`feature-${i}`,date:'2026-10-06',company:'OpenAI',title:`Función independiente ${i}`}))}}));
await stress.goto(url);await stress.locator('.news-cover').first().waitFor();assert.equal(await stress.locator('.news-cover').count(),12);await stress.getByRole('button',{name:'Mostrar más noticias'}).click();assert.equal(await stress.locator('.news-cover').count(),24);await stress.getByLabel('Filtrar por día').fill('2026-10-06');assert.match(await stress.locator('.results-meta').textContent(),/60 noticias/);await stress.close();
assert.deepEqual(errors,[]);await writeFile('qa/browser-results.json',JSON.stringify({passed:true,articles:data.articles.length,errors,checks:['layout order','pagination','search accents','combined company/topic/month/day','filter reload and return','empty pending day','article links/reload/share','320/390/768/1280 reflow','skip keyboard','60 simultaneous launches'],capturedAt:new Date().toISOString()},null,2));await browser.close();console.log('Archive, 60-launch stress scenario, keyboard and responsive checks passed');
