import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('qa',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1916,height:1010},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://127.0.0.1:4173/');await page.getByRole('heading',{name:'Noticias de IA',exact:true}).waitFor();await page.evaluate(()=>document.fonts.ready);
assert.equal(await page.locator('.news-cover').count(),4);
const positions=await page.evaluate(()=>['.archive-masthead','.project-intro','.archive-controls','.archive-results'].map(s=>document.querySelector(s).getBoundingClientRect().top));
assert.deepEqual(positions,[...positions].sort((a,b)=>a-b),'Header → summary → filters → results');
assert.equal(await page.locator('.front-feature,.section-heading').count(),0,'No intervening editorial sections');
await page.screenshot({path:'qa/layout-covers-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Vista lista'}).click();assert.equal(await page.locator('.news-list-item').count(),4);await page.screenshot({path:'qa/layout-list-desktop.png',fullPage:true});
await page.getByRole('searchbox').fill('CREAR imagenes');assert.equal(await page.locator('.news-list-item').count(),1);
await page.getByRole('searchbox').fill('zzzznonexistent');await page.getByRole('heading',{name:'No encontré ediciones con ese filtro'}).waitFor();await page.getByRole('button',{name:'Limpiar filtros'}).click();
await page.getByRole('button',{name:'Google',exact:true}).click();assert.equal(await page.locator('.news-list-item').count(),1);await page.getByRole('button',{name:'Vista portadas'}).click();assert.equal(await page.locator('.news-cover').count(),1);
await page.getByRole('button',{name:/^septiembre$/i}).click();await page.getByRole('heading',{name:'No encontré ediciones con ese filtro'}).waitFor();await page.getByRole('button',{name:'Limpiar filtros'}).click();
await page.getByRole('button',{name:'Modelos',exact:true}).click();assert.equal(await page.locator('.news-cover').count(),3);await page.getByRole('button',{name:'Vista lista'}).click();assert.equal(await page.locator('.news-list-item').count(),3);await page.getByRole('button',{name:'Todos',exact:true}).click();
await page.getByRole('button',{name:'Google',exact:true}).click();await page.locator('.news-list-item').first().click();await page.getByRole('heading',{name:'Consulta la fuente original'}).waitFor();assert.match(page.url(),/#articulo\/nano-banana-2-1$/);await page.reload();await page.getByRole('heading',{name:'Consulta la fuente original'}).waitFor();await page.screenshot({path:'qa/article-desktop.png',fullPage:true});await page.getByRole('link',{name:'Volver a la portada',exact:true}).click();await page.getByRole('button',{name:'Todos',exact:true}).click();await page.getByRole('button',{name:'Vista portadas'}).click();
for(const width of [390,320,768,1280]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false,`Overflow at ${width}px`);if(width===390){await page.screenshot({path:'qa/home-mobile.png',fullPage:true});await page.getByRole('button',{name:'Vista lista'}).click();await page.screenshot({path:'qa/list-mobile.png',fullPage:true});await page.getByRole('button',{name:'Vista portadas'}).click();}}
await page.setViewportSize({width:390,height:844});await page.locator('.news-cover').first().click();await page.getByRole('heading',{name:'Consulta la fuente original'}).waitFor();await page.screenshot({path:'qa/article-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
assert.deepEqual(errors,[]);await writeFile('qa/browser-results.json',JSON.stringify({passed:true,errors,checks:['v4 section order','4 individual covers','4 list rows','search accents','empty/reset','company filter preserved between views','month filter','topic filter preserved between views','article route/reload','320/390/768/1280px overflow','console'],date:new Date().toISOString()},null,2));await browser.close();console.log('Layout and browser checks passed');
